jenkins:
  host: localhost

plugins:
  - plugin: subversion
  - plugin: google-play-android-publisher
  - plugin: envfile
  - plugin: envinject
  - plugin: android-lint
  - plugin: build-name-setter

jobs:
  - job:
      name: Build 
      vcs_provider: subversion
      vcs_url: svn://192.168.32.4/Tuner
      schedule: H/5 * * * *
      buildcmd: $WORKSPACE/gradlew clean buildRelease testRelease
      properties: /hostdir/keystore.properties
      testresults: '**/TEST-*.xml'
      children: Deploy
      version: ${XML,file="app/src/main/AndroidManifest.xml",xpath="//manifest/@versionName"}-${BUILD_NUMBER}

  - job:
      name: Deploy
      vcs_provider: subversion
      vcs_url: svn://192.168.32.4/Tuner
      buildcmd: $WORKSPACE/gradlew clean assembleRelease -Dstore.path=$storepath -Dstore.pwd=$storepwd -Dkey.alias=$keyalias -Dkey.pwd=$keypwd
      properties: /hostdir/keystore.properties
      version: ${XML,file="app/src/main/AndroidManifest.xml",xpath="//manifest/@versionName"}-${BUILD_NUMBER}
      credentials: jenkins-pipeline
      apkfiles: '**/app/build/outputs/apk/app-release.apk'
      releasetrack: 'alpha'
    
