jenkins:
  host: localhost

plugins:
  - plugin: subversion
  - plugin: google-play-android-publisher

jobs:
  -job:
    name: Job1
    vcs_provider: subversion
    vcs_url: svn://192.168.32.4/Tuner
    buildcmd: $WORKSPACE/gradlew assembleDebug
    
